In [1]:
import pandas as pd
import numpy as numpy
import faiss
import matplotlib.pyplot as plt
%matplotlib inline

Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.


In [2]:
mat = numpy.load('filtered_wordvecs.npy')

In [3]:
words = pd.read_csv('vocabulary.txt')

In [4]:
words.columns = ['idf']

In [5]:
from sklearn.neighbors import NearestNeighbors

In [11]:
neigh = NearestNeighbors(n_neighbors=5,p=2, n_jobs=1)

In [18]:
import timeit

In [19]:
start_time = timeit.default_timer()
neigh.fit(mat) 
time_taken = timeit.default_timer() - start_time

In [20]:
print time_taken

14.8850550652


In [26]:
start_time = timeit.default_timer()
neigh.kneighbors(mat[0:5,], 5, return_distance=True)


(array([[ 0.        ,  2.7634916 ,  2.81725997,  2.82374094,  2.84032192],
        [ 0.        ,  0.93499152,  1.03169424,  1.1168656 ,  1.13904639],
        [ 0.        ,  1.25218443,  1.25230258,  1.26372995,  1.26402905],
        [ 0.        ,  3.32038769,  3.57210382,  3.61269729,  3.62478716],
        [ 0.        ,  0.82289595,  0.98526206,  1.0203347 ,  1.03942341]]),
 array([[     0,     26,     40,  17477,     14],
        [     1,     79,     22,  95768,     52],
        [     2,  88598, 108078,  75544,  25296],
        [     3, 123540, 136579, 163603, 198062],
        [     4,     14,     26,     40,     51]]))

In [27]:
start_time = timeit.default_timer()
neigh.kneighbors(mat[0:5,], 5, return_distance=True)
time_taken = timeit.default_timer() - start_time
print time_taken

1.01007294655


In [28]:
import faiss

In [29]:
start_time = timeit.default_timer()
index = faiss.IndexFlatL2(300)   # build the index
# print index.is_trained
xb = mat.astype('float32')
xq = mat.astype('float32')
index.add(xb)
time_taken = timeit.default_timer() - start_time

In [30]:
print time_taken

0.326766014099


In [31]:
k = 5                          # we want to see 4 nearest neighbors
start_time = timeit.default_timer()
D, I = index.search(xb[:5], k) # sanity check
time_taken = timeit.default_timer() - start_time
print time_taken
print I
print D

0.0846600532532
[[     0     26     40  17477     14]
 [     1     79     22  95768     52]
 [     2  88598 108078  75544  25296]
 [     3 123540 136579 163603 198062]
 [     4     14     26     40     51]]
[[  0.           7.63688564   7.93695307   7.97351217   8.06742764]
 [  0.           0.87420905   1.06439281   1.2473886    1.29742646]
 [  0.           1.56796563   1.56826138   1.59701324   1.59776926]
 [  0.          11.02497292  12.75992489  13.05158043  13.13908005]
 [  0.           0.6771577    0.97074127   1.04108286   1.08040094]]
